/**
 * This code was generated by Builder.io.
 */
import React from "react";
import Sidebar from "./Sidebar";
import Header from "./Header";
import LiveFireReports from "./LiveFireReports";
import DispatchedTrucks from "./DispatchedTrucks";
import PendingReports from "./PendingReports";
import Updates from "./Updates";
import TruckManagement from "./TruckManagement";

function Dashboard() {
  return (
    <div className="flex flex-col min-h-screen w-screen bg-slate-100">
      <Header />
      <div className="w-full max-w-full">
        <div className="flex gap-5 max-md:flex-col h-full">
          <Sidebar />
          <main className="flex flex-col w-full h-full">
            <div className="flex flex-col my-auto h-full">
              <div className="flex flex-col w-full">
                <h1 className="text-3xl font-bold leading-none text-gray-900 mt-6 md:mt-8 lg:mt-10">
                  Dashboard
                </h1>
                <div className="mt-5 w-full h-full">
                  <div className="flex gap-5 max-md:flex-col w-full h-full">
                    <div className="flex flex-col w-full h-full">
                      <div className="flex flex-col px-10 py-10 w-full rounded-2xl bg-slate-100 h-full">
                        <div className="flex gap-2 w-full">
                          <LiveFireReports />
                          <DispatchedTrucks />
                        </div>
                        <PendingReports />
                      </div>
                    </div>
                    <Updates />
                  </div>
                </div>
              </div>
              <TruckManagement />
            </div>
          </main>
        </div>
      </div>
    </div>
  );
}

export default Dashboard;

