/**
 * This code was generated by Builder.io.
 */
import React from "react";
import { IoSearch } from "react-icons/io5";

function Header() {
  return (
    <header className="flex overflow-hidden flex-wrap gap-5 justify-between px-20 py-2.5 w-full bg-white max-md:px-5 max-md:max-w-full">
      <div className="flex flex-wrap gap-10 self-start mt-2 text-center text-black whitespace-nowrap max-md:max-w-full">
        <h1 className="my-auto text-2xl font-bold leading-none text-orange-600">
          FireSafe
        </h1>
        <form className="flex overflow-hidden gap-1.5 px-2.5 py-2.5 text-sm leading-none rounded-[50px]">
        <IoSearch  size="28px" className="object-contain shrink-0 w-5 aspect-square mt-2 "/>
        
          <label htmlFor="search" className="sr-only">
            Search
          </label>
          <input
            type="text"
            id="search"
            placeholder="Search..."
            className="px-2 py-2 bg-gray-100 rounded-full outline-none mt-1.5 flex items-center w-full sm:w-72 focus:ring-2 focus:ring-blue-500"
          />
        </form>
      </div>
      <div className="flex gap-8">
        <img
          loading="lazy"
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/8948e0fde731bb733f09c41de360f1b3b90489e458577903331712e953b68b12?placeholderIfAbsent=true&apiKey=f2f1eca11c22487684e8fe7fa994306c"
          className="object-contain shrink-0 my-auto aspect-square w-[25px]"
          alt="Notification icon"
        />
        <img
          loading="lazy"
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/5699272d60faa67b6c1efa2ff17bcb7c90c3cd470f21610725fe2ef3255601f7?placeholderIfAbsent=true&apiKey=f2f1eca11c22487684e8fe7fa994306c"
          className="object-contain shrink-0 aspect-square rounded-[100px] w-[50px]"
          alt="User avatar"
        />
      </div>
    </header>
  );
}

export default Header;
