/**
 * This code was generated by Builder.io.
 */
import React from "react";

function PendingReports() {
  const reports = [
    "+917679****** Just Reported",
    "+917679****** Just Reported",
  ];

  return (
    <div className="flex overflow-hidden flex-col px-12 w-12/12 pt-2.5 pb-8 mt-10 text-sm font-bold leading-9 text-black bg-white rounded-2xl max-md:px-5 max-md:max-w-full">
      <h2 className="self-center text-2xl text-gray-900 leading-[66px]">
        Pending Reports
      </h2>
      {reports.map((report, index) => (
        <div
          key={index}
          className="overflow-hidden px-16 py-2 mt-6 text-center bg-rose-100 rounded-3xl max-md:px-5 max-md:max-w-full"
        >
          {report}
        </div>
      ))}
      <button className="overflow-hidden self-center px-10 py-1.5 mt-6 max-w-full text-center text-white bg-blue-600 rounded-3xl w-[150px] max-md:px-5">
        View More
      </button>
    </div>
  );
}

export default PendingReports;
