/**
 * This code was generated by Builder.io.
 */
import React from "react";

function SearchForm() {
  return (
    <form className="flex overflow-hidden gap-1.5 px-2.5 py-2.5 text-sm leading-none rounded-[50px]">
      <img
        loading="lazy"
        src="https://cdn.builder.io/api/v1/image/assets/TEMP/b848a33cb9a4d496123aa0ea1772eda3b7d5ed4c27b05d6a325237d0d26d082a?placeholderIfAbsent=true&apiKey=f2f1eca11c22487684e8fe7fa994306c"
        className="object-contain shrink-0 w-5 aspect-square"
        alt=""
      />
      <label htmlFor="search" className="sr-only">
        Search
      </label>
      <input
        type="text"
        id="search"
        placeholder="Search..."
        className="flex-auto"
      />
    </form>
  );
}

export default SearchForm;
