/**
 * This code was generated by Builder.io.
 */
import React from "react";

function SidebarItem({ icon, text, active, badge }) {
  const baseClasses =
    "flex gap-4 px-4 py-2.5 text-sm leading-none whitespace-nowrap rounded-[50px]";
  const activeClasses = active
    ? "text-white bg-blue-600"
    : "text-gray-500 bg-slate-100";

  return (
    <div className={`${baseClasses} ${activeClasses}`}>
      <img
        loading="lazy"
        src={icon}
        className="object-contain shrink-0 w-6 aspect-square"
        alt=""
      />
      <div className="grow shrink my-auto w-[161px]">{text}</div>
      {badge && (
        <div className="flex flex-col my-auto text-xs font-bold leading-none text-center text-white">
          <div className="px-2.5 bg-gray-900 rounded-xl">{badge}</div>
        </div>
      )}
    </div>
  );
}

export default SidebarItem;
