/**
 * This code was generated by Builder.io.
 */
import React from "react";

const menuItems = [
  {
    icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/7025711d7f3232784d66e8d0cd727b77f7000f901fa31732ca6516073aadc4b6?placeholderIfAbsent=true&apiKey=f2f1eca11c22487684e8fe7fa994306c",
    text: "Dashboard",
    active: true,
  },
  {
    icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/03a6fe490ecdb9275f9ee5675e3db06a679251bf76d6058c15b388a1a1d33751?placeholderIfAbsent=true&apiKey=f2f1eca11c22487684e8fe7fa994306c",
    text: "Requests",
    badge: 5,
  },
  {
    icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/70dcf82e6e89663a3a1cb5d8c3432102b6dcf7551871fd71f95e65099fe758fd?placeholderIfAbsent=true&apiKey=f2f1eca11c22487684e8fe7fa994306c",
    text: "Management",
  },
  {
    icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/081faf2654a7b65c6eb6ec315da516906c67921b31ce75974a4c4c242bdd289b?placeholderIfAbsent=true&apiKey=f2f1eca11c22487684e8fe7fa994306c",
    text: "Reports",
  },
  {
    icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/f80dcb54ecea4b72d2d99d2f5fa930d44788ffc7f18b3388aabf2cfe7a91199d?placeholderIfAbsent=true&apiKey=f2f1eca11c22487684e8fe7fa994306c",
    text: "Notifications",
  },
  {
    icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/08d28ebd696374b6878253a42fd912504d9effa3dd4259357925d32a403eeb72?placeholderIfAbsent=true&apiKey=f2f1eca11c22487684e8fe7fa994306c",
    text: "Chatbot",
  },
  {
    icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/6610640475fd60e1a316ef92f5e957817203342dff113a763469d8952cf95cc3?placeholderIfAbsent=true&apiKey=f2f1eca11c22487684e8fe7fa994306c",
    text: "Settings",
  },
];

const otherItems = [
  {
    icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/cfd76cd8ac32ba1886ca9d9346eb9acb8834f3743fb4c76fc155c9308bfddbe0?placeholderIfAbsent=true&apiKey=f2f1eca11c22487684e8fe7fa994306c",
    text: "Knowledge Base",
  },
  {
    icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/6c1c189116f27c98f2bc8db547797e3d8311598caaf894265234aa7d283be048?placeholderIfAbsent=true&apiKey=f2f1eca11c22487684e8fe7fa994306c",
    text: "NOCs",
  },
];

function MenuItem({ icon, text, active, badge }) {
  const baseClasses =
    "flex gap-4 px-4 py-2.5 text-sm leading-none whitespace-nowrap rounded-[50px]";
  const activeClasses = active
    ? "text-white bg-blue-600"
    : "text-gray-500 bg-slate-100";

  return (
    <div className={`${baseClasses} ${activeClasses}`}>
      <img
        loading="lazy"
        src={icon}
        className="object-contain shrink-0 w-6 aspect-square"
        alt=""
      />
      <div className="grow shrink my-auto w-[161px]">{text}</div>
      {badge && (
        <div className="flex flex-col my-auto text-xs font-bold leading-none text-center text-white">
          <div className="px-2.5 bg-gray-900 rounded-xl">{badge}</div>
        </div>
      )}
    </div>
  );
}

function Sidebar() {
  return (
    <nav className="flex flex-col w-1/5 max-md:ml-0 max-md:w-full">
      <div className="flex flex-col px-4 pt-4 mx-auto w-full bg-slate-100 pb-[706px] max-md:pb-24">
        {menuItems.map((item, index) => (
          <MenuItem key={index} {...item} />
        ))}
        <div className="self-start mt-3 ml-5 text-xs leading-none text-slate-400 max-md:ml-2.5">
          Other Information
        </div>
        {otherItems.map((item, index) => (
          <MenuItem key={index} {...item} />
        ))}
      </div>
    </nav>
  );
}

export default Sidebar;
