/**
 * This code was generated by Builder.io.
 */
import React from "react";

function StatusCard({ title, content, icon, updateTime }) {
  return (
    <div className="flex overflow-hidden flex-col items-start px-6 pt-5 pb-10 mx-auto w-full font-medium bg-white rounded-3xl leading-[66px] max-md:px-5 max-md:mt-10">
      <h2 className="text-2xl font-bold text-gray-900">{title}</h2>
      <div className="flex z-10 gap-3 self-stretch -mt-3.5 text-base text-center text-black">
        <div className="grow">{content}</div>
        <img
          loading="lazy"
          src={icon}
          className="object-contain shrink-0 my-auto w-10 aspect-square"
          alt=""
        />
      </div>
      <div className="mt-0 text-xs text-center text-green-500">
        {updateTime}
      </div>
    </div>
  );
}

export default StatusCard;
