/**
 * This code was generated by Builder.io.
 */
import React from "react";

function TruckTableRow({ number, location, status, index }) {
  return (
    <React.Fragment>
      <div className="flex flex-col items-start whitespace-nowrap max-md:hidden">
        <div>{index + 1}</div>
      </div>
      <div className="flex flex-col whitespace-nowrap">
        <div className="max-md:mr-0.5">{number}</div>
      </div>
      <div className="flex flex-col whitespace-nowrap">
        <div className="self-start">{location}</div>
      </div>
      <div
        className={`flex flex-col font-medium ${
          status === "Returned" ? "text-blue-700" : "text-green-500"
        }`}
      >
        <div>{status}</div>
      </div>
    </React.Fragment>
  );
}

export default TruckTableRow;
