/**
 * This code was generated by Builder.io.
 */
import React from "react";

function TruckTableHeader() {
  return (
    <div className="flex gap-10 max-w-full w-[862px]">
      <div>Truck No.</div>
      <div className="grow shrink w-[109px]">Truck PL No.</div>
      <div className="grow shrink w-[116px]">Last Location</div>
      <div>Status</div>
    </div>
  );
}

export default TruckTableHeader;
