/**
 * This code was generated by Builder.io.
 */
import React from "react";

function UpdateItem({ text, type }) {
  return (
    <div
      className={`overflow-hidden px-12 py-2 mt-3.5 leading-9 text-center bg-${type}-100 rounded-3xl max-md:px-5`}
    >
      {text}
    </div>
  );
}

export default UpdateItem;
